version: '3.7'

networks:
  internal:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./project:/var/www
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/logs:/var/log/nginx/
    links:
      - php
    networks:
      - internal
  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./project:/var/www
    ports:
      - "8000:8000"
      - "9000:9000"
    links:
      - postgres
    networks:
      - internal
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432" # Проброс портов для внешнего доступа
    volumes:
      - ./database/postgres:/data/postgres
    restart: always # always restart unless stopped manually
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
      POSTGRES_DB: news
    networks:
      - internal